FROM ruby:3.1.2

LABEL maintainer="Sokly Heng <sokly@kawsang.com>"

# Install dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev default-mysql-client nodejs

RUN mkdir /app
WORKDIR /app
ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock
RUN bundle install
ADD . /app

# Copy fonts for PDF rendering
COPY app/assets/fonts /usr/share/fonts
